// Regenerate conformance/vectors.json from the reference implementation.
//   npm run build && node conformance/generate.mjs
//
// Canonical-form vectors are deterministic and language-neutral (no keys): an
// implementation in any language MUST produce the same canonical string for the
// same object. The signature vector carries a public key + signature so other
// implementations can confirm their Ed25519 verification matches.

import { writeFileSync } from "node:fs";
import {
  canonicalObject,
  signAspObject,
  generateDeviceKeyPair,
} from "../packages/open-agent-commerce/dist/index.js";

const ucm = {
  ucm_id: "01H8X7UCM0000000000000000",
  version: "asp-0.1",
  issued_at: "2026-01-01T00:00:00.000Z",
  expires_at: "2027-01-01T00:00:00.000Z",
  user_id: "usr_demo",
  device_id: "dev_demo",
  idp: "https://vyana.ai",
  kyc_level: 2,
  authenticator_tier: 2,
  caps: { monthly_paise: 500000, per_txn_paise: 100000, daily_paise: 200000 },
  allowed_categories: ["saas"],
  allowed_services: ["example.com"],
  signature_alg: "EdDSA",
  signature: "PLACEHOLDER",
};

const signupMandate = {
  mandate_id: "01J9SIGNUP000000000000000",
  ucm_id: ucm.ucm_id,
  version: "asp-0.1",
  issued_at: "2026-06-03T10:00:00.000Z",
  expires_at: "2026-06-03T10:10:00.000Z",
  nonce: "9f2c1a",
  user_id: "usr_demo",
  device_id: "dev_demo",
  agent: { platform: "claude", session_id: "sess_1", version: "1.0.0" },
  idp: "https://vyana.ai",
  service: "example.com",
  plan: "pro-monthly",
  config: {},
  max_cost_paise: 49900,
  allowed_strategies: ["native-asp", "oauth-app"],
  consent_budget: "one-tap",
  user_raw_message: "sign me up for the pro plan on example.com",
  signature_alg: "EdDSA",
  signature: "PLACEHOLDER",
};

const cartMandate = {
  mandate_id: "01J9CART00000000000000000",
  ucm_id: ucm.ucm_id,
  version: "asp-0.1",
  issued_at: "2026-06-03T10:00:00.000Z",
  expires_at: "2026-06-03T10:10:00.000Z",
  nonce: "abc123",
  user_id: "usr_demo",
  device_id: "dev_demo",
  idp: "https://vyana.ai",
  service: "example.com",
  line_items: [{ description: "Pro plan", amount_paise: 49900 }],
  amount_paise: 49900,
  currency: "INR",
  reason: "subscription",
  consent_budget: "one-tap",
  user_raw_message: "pay 499 for the pro plan",
  signature_alg: "EdDSA",
  signature: "PLACEHOLDER",
};

const canonical = [
  { name: "user-consent-mandate", object: ucm, canonical: canonicalObject(ucm) },
  { name: "signup-mandate", object: signupMandate, canonical: canonicalObject(signupMandate) },
  { name: "cart-mandate", object: cartMandate, canonical: canonicalObject(cartMandate) },
];

// One signed vector: sign the signup mandate; store pubkey + signature (no priv).
const { privateKeyPem, publicKeyDerBase64 } = generateDeviceKeyPair();
const signed = { ...signupMandate };
signed.signature = signAspObject(signed, privateKeyPem);

const out = {
  note: "Generated by conformance/generate.mjs. Canonical vectors are key-free and deterministic. Verify them with conformance/run.mjs.",
  asp_version: "asp-0.1",
  canonical,
  signatureVectors: [
    {
      name: "signup-mandate-ed25519",
      object: signed,
      publicKeyDerBase64,
      algorithm: "EdDSA",
      expectVerify: true,
    },
  ],
};

writeFileSync(
  new URL("./vectors.json", import.meta.url),
  JSON.stringify(out, null, 2) + "\n",
);
console.log("wrote conformance/vectors.json");
